---
abstract: 'Inotify-based file tail watcher'
author:
  - 'Ivan Baidakou <dmol@gmx.com>'
build_requires:
  Path::Tiny: 0.051
  Test::More: 0.98
  Test::Warnings: 0.013
configure_requires:
  ExtUtils::MakeMaker: 6.72
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PerlWatcher-Watcher-FileTail
requires:
  AnyEvent: 7.04
  App::PerlWatcher::Engine: 0.19
  Devel::Comments: v1.1.4
  File::ReadBackwards: 1.05
  Linux::Inotify2: 1.22
  List::MoreUtils: 0.33
  Moo: 1.003000
  Path::Class: 0.32
  aliased: 0.31
  perl: 5.012
version: 0.18
